---
version: '3'
networks:
  net:

services:
  redis:
    image: redis:7.2.3-alpine3.18
    networks: [net]
    restart: always
    command:
      - 'redis-server'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 100'
    volumes:
      - /mnt/docker/redis/data:/data

  frigate-telegram:
    image: ghcr.io/mikevlz/frigate-telegram:amd64
    restart: always
    networks: [net]
    environment:
      TELEGRAM_BOT_TOKEN: 1234567890:ABCDEFGHEFGREHBTYJBTRGBER34T54Y54
      FRIGATE_URL: http://192.168.0.254:5000
      FRIGATE_EVENT_LIMIT: 5
      DEBUG: False
      TELEGRAM_CHAT_ID: "0"
      SLEEP_TIME: 30
      FRIGATE_EXTERNAL_URL: https://frigate.domain.com
      TZ: Europe/Berlin
      REDIS_ADDR: "redis:6379"
    volumes:
      - type: tmpfs # Optional
        target: /tmp
        tmpfs:
          size: 10000000
